name: at_virtual_suggestion_box
description: A team  project for @company credentials

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  modal_progress_hud: any
  at_demo_data: ^0.0.3+1 
  at_server_status: ^0.1.0+1
  at_chat_flutter: ^0.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true

  #To add assets to your application, add an assets section, like this:
  assets:
    - images/sugg.png
    - images/team.png
    - images/atsign.png
    - images/Rose-petals.png
    - images/Confetti-Doodles.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
